"""Removing location form Event

Revision ID: 27516b8ef758
Revises: c0f16f73b5d7
Create Date: 2017-06-28 13:49:21.149690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27516b8ef758'
down_revision = 'c0f16f73b5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
