"""create locations table

Revision ID: 979247b9793c
Revises: c3aebb03a1a1
Create Date: 2017-06-28 13:14:53.255027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979247b9793c'
down_revision = 'c3aebb03a1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event_actors', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_actors', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_actors', type_='foreignkey')
    op.drop_column('event_actors', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
