"""baseline

Revision ID: afe2a81bc509
Revises: 2f0d41fa6d4a
Create Date: 2017-06-21 14:36:01.125790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe2a81bc509'
down_revision = '2f0d41fa6d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
