"""Moving location from eventActor to Event

Revision ID: c0f16f73b5d7
Revises: 6d4400ee3832
Create Date: 2017-06-28 13:43:50.605304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f16f73b5d7'
down_revision = '6d4400ee3832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_actors_location_id_fkey', 'event_actors', type_='foreignkey')
    op.drop_column('event_actors', 'location_id')
    op.add_column('events', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'location_id')
    op.add_column('event_actors', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_actors_location_id_fkey', 'event_actors', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
