"""Test One to many

Revision ID: cb04a13d70ac
Revises: df70215da3eb
Create Date: 2017-06-28 15:28:08.871840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb04a13d70ac'
down_revision = 'df70215da3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
