"""test

Revision ID: d1bc8ea2c8ee
Revises: d578ec92d18b
Create Date: 2017-06-28 15:00:47.326441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bc8ea2c8ee'
down_revision = 'd578ec92d18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
