"""One_location_to_many_events

Revision ID: d3fd10481f76
Revises: 27516b8ef758
Create Date: 2017-06-28 14:04:01.569357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fd10481f76'
down_revision = '27516b8ef758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
