"""Fu

Revision ID: dc277ebd993c
Revises: fc9313383801
Create Date: 2017-06-28 14:12:04.836850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc277ebd993c'
down_revision = 'fc9313383801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
