"""Fu

Revision ID: fc9313383801
Revises: 5b4d123efbd6
Create Date: 2017-06-28 14:06:13.480054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9313383801'
down_revision = '5b4d123efbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
