"""empty message

Revision ID: 3f45728e5a4c
Revises: e3fdab73bfd5
Create Date: 2017-06-06 13:44:27.548627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f45728e5a4c'
down_revision = 'e3fdab73bfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('armors', 'range_increment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('armors', sa.Column('range_increment', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
