"""empty message

Revision ID: 5b30040514d8
Revises: 1b002250b0d1
Create Date: 2017-06-06 17:41:58.358027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b30040514d8'
down_revision = '1b002250b0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adventures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('events', sa.String(), nullable=True),
    sa.Column('encounters', sa.String(), nullable=True),
    sa.Column('players', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adventure_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('players', sa.String(), nullable=True),
    sa.Column('allies', sa.String(), nullable=True),
    sa.Column('opponents', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('adventure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'adventures', ['adventure_id'], ['id'])
    op.drop_column('events', 'weight')
    op.drop_column('events', 'speed_9m')
    op.drop_column('events', 'dmg_type')
    op.drop_column('events', 'cost')
    op.drop_column('events', 'max_dex')
    op.drop_column('events', 'speed_6m')
    op.drop_column('events', 'arcane_spell_fail')
    op.drop_column('events', 'armor_penalty_check')
    op.drop_column('events', 'ca_bonus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ca_bonus', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('armor_penalty_check', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('arcane_spell_fail', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('speed_6m', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('max_dex', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('dmg_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('speed_9m', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'adventure_id')
    op.drop_table('encounters')
    op.drop_table('adventures')
    # ### end Alembic commands ###
