"""empty message

Revision ID: 6c0b7e392f93
Revises: fe5907f01b3a
Create Date: 2017-06-14 14:28:50.891427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c0b7e392f93'
down_revision = 'fe5907f01b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adventures')
    op.drop_table('classes')
    op.drop_table('encounters')
    op.drop_table('armors')
    op.drop_table('events')
    op.drop_table('weapons')
    op.drop_table('chars')
    op.drop_table('races')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('races',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('races_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='races_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chars',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('klass_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_hp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_hp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('str', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dex', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('con', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wis', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cha', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('BAB', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AC_natural', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('magic_resist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AC', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AC_flatfooted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AC_touch', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('initiative', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_speed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SAVE_ref', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SAVE_for', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SAVE_will', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spells', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feats', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('right_hand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shield_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('armor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('head_protection', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hand_protection', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inventory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['armor_id'], ['armors.id'], name='chars_armor_id_fkey'),
    sa.ForeignKeyConstraint(['klass_id'], ['classes.id'], name='chars_klass_id_fkey'),
    sa.ForeignKeyConstraint(['left_hand_id'], ['weapons.id'], name='chars_left_hand_id_fkey'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name='chars_race_id_fkey'),
    sa.ForeignKeyConstraint(['right_hand_id'], ['weapons.id'], name='chars_right_hand_id_fkey'),
    sa.ForeignKeyConstraint(['shield_id'], ['armors.id'], name='chars_shield_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chars_pkey')
    )
    op.create_table('weapons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dmg_S', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dmg_M', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('critical', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('range_increment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dmg_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='weapons_pkey')
    )
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adventure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], name='events_adventure_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_table('armors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_shield', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ca_bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_dex', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('armor_penalty_check', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('arcane_spell_fail', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speed_6m', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('speed_9m', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dmg_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='armors_pkey')
    )
    op.create_table('encounters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('adventure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('players', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('allies', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('opponents', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventures.id'], name='encounters_adventure_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='encounters_pkey')
    )
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='classes_pkey')
    )
    op.create_table('adventures',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('events', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('encounters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('players', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='adventures_pkey')
    )
    # ### end Alembic commands ###
