"""empty message

Revision ID: e3fdab73bfd5
Revises: 
Create Date: 2017-06-06 13:38:50.974409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fdab73bfd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_shield', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ca_bonus', sa.Integer(), nullable=True),
    sa.Column('range_increment', sa.Integer(), nullable=True),
    sa.Column('max_dex', sa.Integer(), nullable=True),
    sa.Column('armor_penalty_check', sa.Integer(), nullable=True),
    sa.Column('arcane_spell_fail', sa.Integer(), nullable=True),
    sa.Column('speed_6m', sa.Integer(), nullable=True),
    sa.Column('speed_9m', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dmg_type', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weapons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dmg_S', sa.String(), nullable=True),
    sa.Column('dmg_M', sa.String(), nullable=True),
    sa.Column('critical', sa.String(), nullable=True),
    sa.Column('range_increment', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('dmg_type', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('klass_id', sa.Integer(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('total_hp', sa.Integer(), nullable=True),
    sa.Column('str', sa.Integer(), nullable=True),
    sa.Column('dex', sa.Integer(), nullable=True),
    sa.Column('con', sa.Integer(), nullable=True),
    sa.Column('int', sa.Integer(), nullable=True),
    sa.Column('wis', sa.Integer(), nullable=True),
    sa.Column('cha', sa.Integer(), nullable=True),
    sa.Column('BAB', sa.Integer(), nullable=True),
    sa.Column('AC_natural', sa.Integer(), nullable=True),
    sa.Column('magic_resist', sa.Integer(), nullable=True),
    sa.Column('AC', sa.Integer(), nullable=True),
    sa.Column('AC_flatfooted', sa.Integer(), nullable=True),
    sa.Column('AC_touch', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('initiative', sa.Integer(), nullable=True),
    sa.Column('base_speed', sa.Integer(), nullable=True),
    sa.Column('SAVE_ref', sa.Integer(), nullable=True),
    sa.Column('SAVE_for', sa.Integer(), nullable=True),
    sa.Column('SAVE_will', sa.Integer(), nullable=True),
    sa.Column('spells', sa.String(), nullable=True),
    sa.Column('feats', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('right_hand_id', sa.Integer(), nullable=True),
    sa.Column('left_hand_id', sa.Integer(), nullable=True),
    sa.Column('shield_id', sa.Integer(), nullable=True),
    sa.Column('armor_id', sa.Integer(), nullable=True),
    sa.Column('head_protection', sa.String(), nullable=True),
    sa.Column('hand_protection', sa.String(), nullable=True),
    sa.Column('inventory', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['armor_id'], ['armors.id'], ),
    sa.ForeignKeyConstraint(['klass_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['left_hand_id'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['right_hand_id'], ['weapons.id'], ),
    sa.ForeignKeyConstraint(['shield_id'], ['armors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chars')
    op.drop_table('weapons')
    op.drop_table('races')
    op.drop_table('classes')
    op.drop_table('armors')
    # ### end Alembic commands ###
