"""empty message

Revision ID: fe5907f01b3a
Revises: 5b30040514d8
Create Date: 2017-06-06 17:44:45.366783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5907f01b3a'
down_revision = '5b30040514d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adventures', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adventures', 'name')
    # ### end Alembic commands ###
